name: Continuous Integration (E2E Testing Checks without metrics database)

on:
  workflow_call:
jobs:
  e2e-no-metrics-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo from current commit
        uses: actions/checkout@v3
      - name: set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          check-latest: true
          cache: true
      - name: pull pre-built images
        run: sudo docker compose -f ci.docker-compose-no-metrics.yml pull
      - name: build and start proxy service and it's dependencies
        run: sudo docker compose -f ci.docker-compose-no-metrics.yml up -d --build
      - name: wait for proxy service to be running
        run: bash ${GITHUB_WORKSPACE}/scripts/wait-for-proxy-service-running.sh
        env:
            PROXY_CONTAINER_PORT: 7777
      - name: run e2e tests
        run: make e2e-test-no-metrics
      - name: print proxy service logs
        run: sudo docker compose -f ci.docker-compose-no-metrics.yml logs proxy
        # because we especially want the logs if the test(s) fail 😅
        if: always()
      # Finally, "Post Run jpribyl/action-docker-layer-caching@v0.1.1",
      # which is the process of saving the cache, will be executed.
