name: Continuous Integration (Main Branch)
on:
  push:
    # run CI on any push to the main branch
    branches:
      - main
jobs:
  # run per commit ci checks against main branch
  lint-checks:
    uses: ./.github/workflows/ci-lint.yml
  # run default ci checks against main branch
  default-checks:
    uses: ./.github/workflows/ci-default.yml
  # run e2e testing ci for internal testnet checks against main branch
  e2e-tests:
    needs: [lint-checks, default-checks]
    uses: ./.github/workflows/ci-e2e-tests.yml
  # run e2e testing without metrics db ci for internal testnet checks against main branch
  e2e-no-metrics-tests:
    needs: [lint-checks, default-checks]
    uses: ./.github/workflows/ci-e2e-no-metrics-tests.yml
  # build, tag and publish new service docker images
  release-docker-images:
      needs: [e2e-tests]
      uses: ./.github/workflows/ci-docker-release.yml
      with:
        dockerhub-username: kavaops
      secrets: inherit
