name: Continuous Integration (Kava Proxy Service Main)
on:
  push:
    # run CI on any push to the main branch
    branches:
      - main
jobs:
  # run per commit ci checks against main branch
  lint-checks:
    uses: ./.github/workflows/ci-lint.yml
  # run default ci checks against main branch
  default-checks:
    uses: ./.github/workflows/ci-default.yml
  # run e2e testing ci checks against main branch
  e2e-tests:
    needs: [lint-checks, default-checks]
    uses: ./.github/workflows/ci-e2e-tests.yml
