name: Continuous Integration (PR)
on:
  pull_request:
    # run CI on pull requests to main or a release branch
    branches:
      - main
      - 'releases/**'
# run default ci checks against current PR
jobs:
  default:
    uses: ./.github/workflows/ci-default.yml
  e2e-tests:
    uses: ./.github/workflows/ci-e2e-tests.yml
  e2e-local-test:
    uses: ./.github/workflows/ci-e2e-local-tests.yml
  e2e-no-metrics-tests:
    uses: ./.github/workflows/ci-e2e-no-metrics-tests.yml
